## Import du dataframe

In [30]:
import pandas as pd
import numpy as np

# Bibliothèques pour la visualisation
import matplotlib.pyplot as plt
import seaborn as sns

df_household = pd.read_csv('../data/src/household.csv', sep=';', dtype={'GEO': str})
df_population = pd.read_csv('../data/src/population.csv', sep=';', dtype={'GEO': str})
df_conjugality = pd.read_csv('../data/src/conjugality.csv', sep=';', dtype={'GEO': str})
df_election =  pd.read_csv('../data/src/election.csv', sep=';', dtype={'Code_INSEE': str})

display(df_household)
display(df_election)
display(df_population)

,GEO,PCS,TPH,OBS_VALUE,CITY
0,56009,Total,Famille principale couple avec enfants,390.977210,Bangor
1,55385,Total,Homme seul,36.689838,Nixéville-Blercourt
2,56135,Total,Ménage comprenant une famille,1418.610455,Molac
3,55331,Total,Total,74.000000,Méligny-le-Petit
4,54479,Total,Ménage à une personne,11.333333,Saint-Mard
...,...,...,...,...,...
260015,57056,Total,Total,189.000000,Bébing
260016,57053,Total,Total,107.000000,Bassing
260017,57001,Total,Ménage à une personne,24.320200,Aboncourt
260018,57003,Total,Famille principale couple avec enfants,569.893701,Abreschviller
260019,56223,Total,Ménage à une personne,211.894218,Saint-Jean-la-Poterie

,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,pct_abstention,pct_blancs,pct_nuls,pct_gauche,pct_centre,pct_droite
0,01001,L'Abergement-Clémenciat,645,108,537,16,1,520,16.74,2.98,0.19,21.73,32.31,45.96
1,01002,L'Abergement-de-Varey,213,38,175,3,1,171,17.84,1.71,0.57,38.60,35.09,26.32
2,01004,Ambérieu-en-Bugey,8765,2078,6687,88,46,6553,23.71,1.32,0.69,34.44,24.87,40.68
3,01005,Ambérieux-en-Dombes,1282,234,1048,14,6,1028,18.25,1.34,0.57,21.50,29.47,49.03
4,01006,Ambléon,103,23,80,3,0,77,22.33,3.75,0.00,32.47,29.87,37.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35224,ZZ229,Zurich,24868,14101,10767,40,31,10696,56.70,0.37,0.29,26.67,54.92,18.41
35225,ZZ231,Taipei,1709,942,767,8,2,757,55.12,1.04,0.26,37.38,39.23,23.38
35226,ZZ233,Nour-Soultan,117,64,53,2,0,51,54.70,3.77,0.00,27.45,50.98,21.57
35227,ZZ234,Monterrey,713,553,160,0,2,158,77.56,0.00,1.25,20.89,61.39,17.72
35228,ZZ235,Bahamas (Nassau),136,78,58,3,0,55,57.35,5.17,0.00,5.45,45.45,49.09

,AGE,GEO,SOCIO_PROF_CAT,SEX,POPULATION,CITY
0,55 ans ou plus,02168,Professions intermédiaires,Femme,101.479097,Château-Thierry
1,De 25 à 54 ans,02157,Employés,Femme,40.174901,Chambry
2,55 ans ou plus,24551,Retraités,Homme,412.982285,Thiviers
3,55 ans ou plus,29155,Retraités,Femme,203.650001,Ouessant
4,De 15 à 24 ans,27681,Ouvriers,Homme,227.470055,Vernon
...,...,...,...,...,...,...
2233693,15 ans ou plus,95141,Total,Homme,22.000000,Charmont
2233694,De 15 à 24 ans,93061,Total,Homme,904.953279,Le Pré-Saint-Gervais
2233695,15 ans ou plus,92060,Total,Homme,11274.039432,Le Plessis-Robinson
2233696,15 ans ou plus,95213,Total,Total,522.959730,Épiais-Rhus
2233697,15 ans ou plus,94048,Total,Homme,1871.112012,Marolles-en-Brie

In [31]:
#df_household[df_household["GEO"] == "56008"]

In [32]:
df_household["TPH"].unique()
df_population["AGE"].unique()
df_population["SOCIO_PROF_CAT"].unique()

<StringArray>
[                       'Professions intermédiaires',
                                          'Employés',
                                         'Retraités',
                                          'Ouvriers',
 'Cadres et professions intellectuelles supérieures',
                                   'Autres inactifs',
                                      'Agriculteurs',
       'Artisans, commerçants et chefs d’entreprise',
                                             'Total']
Length: 9, dtype: str

In [33]:
df_household_line = (
    df_household.pivot_table(
        index=["GEO", "CITY"],
        columns="TPH",
        values="OBS_VALUE",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

display(df_household_line)

TPH,GEO,CITY,Famille principale couple avec enfants,Famille principale couple sans enfants,Famille principale monoparentale,Femme seule,Homme seul,Ménage comprenant une famille,Ménage sans famille à plusieurs personnes,Ménage à une personne,Total
0,10002,Ailleville,81.617355,79.508247,23.425759,27.463314,10.985325,184.551361,0.000000,38.448639,223.000000
1,10003,Aix-Villemaur-Pâlis,1318.732819,1064.587185,265.840077,303.373495,288.694133,2649.160081,20.150397,592.067628,3261.378105
2,10004,Allibaudières,93.873704,52.152058,15.645617,10.430412,10.430412,161.671379,10.430412,20.860823,192.962614
3,10005,Amance,97.622791,94.899149,0.000000,41.182449,10.295612,192.521939,0.000000,51.478061,244.000000
4,10006,Arcis-sur-Aube,903.761393,716.171522,480.392539,324.403512,219.555106,2100.325453,39.697953,543.958618,2683.982024
...,...,...,...,...,...,...,...,...,...,...,...
31818,97420,Sainte-Suzanne,12760.424567,3199.598722,6334.214362,1093.195306,1048.972476,22294.237650,318.312164,2142.167782,24754.717596
31819,97421,Salazie,3967.876046,1120.690862,1415.664358,248.383089,462.895757,6504.231266,114.864384,711.278846,7330.374496
31820,97422,Le Tampon,36126.634450,14708.900805,18227.488136,5511.752464,5313.125830,69063.023391,1562.767012,10824.878294,81450.668697
31821,97423,Les Trois-Bassins,3743.670058,883.399799,1538.422129,299.633441,440.969970,6165.491986,207.081713,740.603411,7113.177109
31822,97424,Cilaos,2336.799933,942.418805,1181.739919,275.836650,403.538802,4460.958657,71.998652,679.375452,5212.332761

In [34]:
df = df_household_line.merge(
    df_election,
    left_on="GEO",
    right_on="Code_INSEE",
    how="inner"
)

display(df)

,GEO,CITY,Famille principale couple avec enfants,Famille principale couple sans enfants,Famille principale monoparentale,Femme seule,Homme seul,Ménage comprenant une famille,Ménage sans famille à plusieurs personnes,Ménage à une personne,...,Votants,Blancs,Nuls,Exprimés,pct_abstention,pct_blancs,pct_nuls,pct_gauche,pct_centre,pct_droite
0,10002,Ailleville,81.617355,79.508247,23.425759,27.463314,10.985325,184.551361,0.000000,38.448639,...,154,1,0,153,22.22,0.65,0.00,25.49,28.76,45.75
1,10003,Aix-Villemaur-Pâlis,1318.732819,1064.587185,265.840077,303.373495,288.694133,2649.160081,20.150397,592.067628,...,1978,24,14,1940,25.08,1.21,0.71,22.22,25.05,52.73
2,10004,Allibaudières,93.873704,52.152058,15.645617,10.430412,10.430412,161.671379,10.430412,20.860823,...,118,2,1,115,25.79,1.69,0.85,11.30,20.00,68.70
3,10005,Amance,97.622791,94.899149,0.000000,41.182449,10.295612,192.521939,0.000000,51.478061,...,154,6,2,146,24.88,3.90,1.30,16.44,26.03,57.53
4,10006,Arcis-sur-Aube,903.761393,716.171522,480.392539,324.403512,219.555106,2100.325453,39.697953,543.958618,...,1309,21,10,1278,29.59,1.60,0.76,19.87,26.45,53.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31573,95676,Villers-en-Arthies,277.866607,111.793995,45.405640,31.160255,20.773503,435.066242,0.000000,51.933758,...,340,2,0,338,12.82,0.59,0.00,26.63,27.51,45.86
31574,95678,Villiers-Adam,503.811765,219.482353,39.905882,24.941176,59.858824,763.200000,0.000000,84.800000,...,531,9,5,517,11.94,1.69,0.94,25.73,31.33,42.94
31575,95680,Villiers-le-Bel,16868.584767,3046.680721,5391.485967,1432.820914,1414.116321,25306.751455,556.640496,2846.937235,...,8388,106,76,8206,32.36,1.26,0.91,59.10,19.34,21.56
31576,95682,Villiers-le-Sec,136.714286,47.142857,0.000000,4.714286,9.428571,183.857143,0.000000,14.142857,...,96,0,1,95,12.73,0.00,1.04,31.58,29.47,38.95
31577,95690,Wy-dit-Joli-Village,135.777778,104.444444,15.666667,26.111111,26.111111,255.888889,20.888889,52.222222,...,237,4,2,231,16.84,1.69,0.84,28.57,31.60,39.83

In [35]:
df["Votants"].sum().item()

32513905

In [36]:
df_election["Votants"].sum().item()

35918991

In [37]:
df.columns

Index(['GEO', 'CITY', 'Famille principale couple avec enfants',
       'Famille principale couple sans enfants',
       'Famille principale monoparentale', 'Femme seule', 'Homme seul',
       'Ménage comprenant une famille',
       'Ménage sans famille à plusieurs personnes ', 'Ménage à une personne',
       'Total', 'Code_INSEE', 'Libellé de la commune', 'Inscrits',
       'Abstentions', 'Votants', 'Blancs', 'Nuls', 'Exprimés',
       'pct_abstention', 'pct_blancs', 'pct_nuls', 'pct_gauche', 'pct_centre',
       'pct_droite'],
      dtype='str')

In [38]:
df =df.drop('Code_INSEE', axis=1)
df =df.drop('Libellé de la commune', axis=1)

In [39]:
display(df)

,GEO,CITY,Famille principale couple avec enfants,Famille principale couple sans enfants,Famille principale monoparentale,Femme seule,Homme seul,Ménage comprenant une famille,Ménage sans famille à plusieurs personnes,Ménage à une personne,...,Votants,Blancs,Nuls,Exprimés,pct_abstention,pct_blancs,pct_nuls,pct_gauche,pct_centre,pct_droite
0,10002,Ailleville,81.617355,79.508247,23.425759,27.463314,10.985325,184.551361,0.000000,38.448639,...,154,1,0,153,22.22,0.65,0.00,25.49,28.76,45.75
1,10003,Aix-Villemaur-Pâlis,1318.732819,1064.587185,265.840077,303.373495,288.694133,2649.160081,20.150397,592.067628,...,1978,24,14,1940,25.08,1.21,0.71,22.22,25.05,52.73
2,10004,Allibaudières,93.873704,52.152058,15.645617,10.430412,10.430412,161.671379,10.430412,20.860823,...,118,2,1,115,25.79,1.69,0.85,11.30,20.00,68.70
3,10005,Amance,97.622791,94.899149,0.000000,41.182449,10.295612,192.521939,0.000000,51.478061,...,154,6,2,146,24.88,3.90,1.30,16.44,26.03,57.53
4,10006,Arcis-sur-Aube,903.761393,716.171522,480.392539,324.403512,219.555106,2100.325453,39.697953,543.958618,...,1309,21,10,1278,29.59,1.60,0.76,19.87,26.45,53.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31573,95676,Villers-en-Arthies,277.866607,111.793995,45.405640,31.160255,20.773503,435.066242,0.000000,51.933758,...,340,2,0,338,12.82,0.59,0.00,26.63,27.51,45.86
31574,95678,Villiers-Adam,503.811765,219.482353,39.905882,24.941176,59.858824,763.200000,0.000000,84.800000,...,531,9,5,517,11.94,1.69,0.94,25.73,31.33,42.94
31575,95680,Villiers-le-Bel,16868.584767,3046.680721,5391.485967,1432.820914,1414.116321,25306.751455,556.640496,2846.937235,...,8388,106,76,8206,32.36,1.26,0.91,59.10,19.34,21.56
31576,95682,Villiers-le-Sec,136.714286,47.142857,0.000000,4.714286,9.428571,183.857143,0.000000,14.142857,...,96,0,1,95,12.73,0.00,1.04,31.58,29.47,38.95
31577,95690,Wy-dit-Joli-Village,135.777778,104.444444,15.666667,26.111111,26.111111,255.888889,20.888889,52.222222,...,237,4,2,231,16.84,1.69,0.84,28.57,31.60,39.83

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31578 entries, 0 to 31577
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   GEO                                         31578 non-null  str
 1   CITY                                        31578 non-null  str
 2   Famille principale couple avec enfants      31578 non-null  float64
 3   Famille principale couple sans enfants      31578 non-null  float64
 4   Famille principale monoparentale            31578 non-null  float64
 5   Femme seule                                 31578 non-null  float64
 6   Homme seul                                  31578 non-null  float64
 7   Ménage comprenant une famille               31578 non-null  float64
 8   Ménage sans famille à plusieurs personnes   31578 non-null  float64
 9   Ménage à une personne                       31578 non-null  float64
 10  Total                                       31578 non-null  float64
 11  Inscrits                                    31578 non-null  int64
 12  Abstentions                                 31578 non-null  int64
 13  Votants                                     31578 non-null  int64
 14  Blancs                                      31578 non-null  int64
 15  Nuls                                        31578 non-null  int64
 16  Exprimés                                    31578 non-null  int64
 17  pct_abstention                              31578 non-null  float64
 18  pct_blancs                                  31578 non-null  float64
 19  pct_nuls                                    31578 non-null  float64
 20  pct_gauche                                  31578 non-null  float64
 21  pct_centre                                  31578 non-null  float64
 22  pct_droite                                  31578 non-null  float64
dtypes: float64(15), int64(6), str(2)
memory usage: 5.5 MB

In [41]:
# df_gauche = df.pop('pct_gauche')
# df_centre = df.pop('pct_centre')
# df_droite = df.pop('pct_droite')

In [42]:
top_5 = df.sort_values(by="Votants", ascending=False).head(5)

top_5[["CITY", "Votants"]]

            CITY  Votants
26031      Paris  1071357
1202   Marseille   354016
23876       Lyon   239843
8624    Toulouse   200207
13112     Nantes   148738

In [ ]:
df['Homme_seul_en_pct'] = (df['Homme seul'] / df['Total']) * 100
df['Femme_seul_en_pct'] = (df['Femme seule'] / df['Total']) * 100
df['Fpcae_en_pct'] = (df['Famille principale couple avec enfants'] / df['Total']) * 100
df['Fpcse_en_pct'] = (df['Famille principale couple sans enfants'] / df['Total']) * 100
df['Fpm_en_pct'] = (df['Famille principale monoparentale'] / df['Total']) * 100 
df['Mcuf_en_pct'] = (df['Ménage comprenant une famille'] / df['Total']) * 100 #1 147h
df['Msfapp_en_pct'] = (df['Ménage sans famille à plusieurs personnes '] / df['Total']) * 100
df['Maup_en_pct'] = (df['Ménage à une personne'] / df['Total']) * 100

display(df)

,GEO,CITY,Famille principale couple avec enfants,Famille principale couple sans enfants,Famille principale monoparentale,Femme seule,Homme seul,Ménage comprenant une famille,Ménage sans famille à plusieurs personnes,Ménage à une personne,...,pct_centre,pct_droite,Homme_seul_en_pct,Femme_seul_en_pct,Fpcae_en_pct,Fpcse_en_pct,Fpm_en_pct,Mcuf_en_pct,Maup_en_pct,Msfapp_en_pct
0,10002,Ailleville,81.617355,79.508247,23.425759,27.463314,10.985325,184.551361,0.000000,38.448639,...,28.76,45.75,4.926155,12.315387,36.599711,35.653922,10.504825,82.758458,17.241542,0.000000
1,10003,Aix-Villemaur-Pâlis,1318.732819,1064.587185,265.840077,303.373495,288.694133,2649.160081,20.150397,592.067628,...,25.05,52.73,8.851906,9.302003,40.434834,32.642250,8.151158,81.228241,18.153909,0.617849
2,10004,Allibaudières,93.873704,52.152058,15.645617,10.430412,10.430412,161.671379,10.430412,20.860823,...,20.00,68.70,5.405406,5.405406,48.648649,27.027027,8.108108,83.783784,10.810811,5.405406
3,10005,Amance,97.622791,94.899149,0.000000,41.182449,10.295612,192.521939,0.000000,51.478061,...,26.03,57.53,4.219513,16.878053,40.009341,38.893094,0.000000,78.902434,21.097566,0.000000
4,10006,Arcis-sur-Aube,903.761393,716.171522,480.392539,324.403512,219.555106,2100.325453,39.697953,543.958618,...,26.45,53.68,8.180200,12.086650,33.672409,26.683171,17.898501,78.254080,20.266850,1.479069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31573,95676,Villers-en-Arthies,277.866607,111.793995,45.405640,31.160255,20.773503,435.066242,0.000000,51.933758,...,27.51,45.86,4.265606,6.398410,57.056798,22.955646,9.323540,89.335984,10.664016,0.000000
31574,95678,Villiers-Adam,503.811765,219.482353,39.905882,24.941176,59.858824,763.200000,0.000000,84.800000,...,31.33,42.94,7.058824,2.941176,59.411765,25.882353,4.705882,90.000000,10.000000,0.000000
31575,95680,Villiers-le-Bel,16868.584767,3046.680721,5391.485967,1432.820914,1414.116321,25306.751455,556.640496,2846.937235,...,19.34,21.56,4.925462,4.990611,58.754411,10.611793,18.778907,88.145111,9.916073,1.938816
31576,95682,Villiers-le-Sec,136.714286,47.142857,0.000000,4.714286,9.428571,183.857143,0.000000,14.142857,...,29.47,38.95,4.761905,2.380953,69.047619,23.809524,0.000000,92.857143,7.142857,0.000000
31577,95690,Wy-dit-Joli-Village,135.777778,104.444444,15.666667,26.111111,26.111111,255.888889,20.888889,52.222222,...,31.60,39.83,7.936508,7.936508,41.269841,31.746032,4.761905,77.777778,15.873016,6.349206

In [67]:
filtered = df[df["Total"] > 100]

display(filtered)

,GEO,CITY,Famille principale couple avec enfants,Famille principale couple sans enfants,Famille principale monoparentale,Femme seule,Homme seul,Ménage comprenant une famille,Ménage sans famille à plusieurs personnes,Ménage à une personne,...,pct_centre,pct_droite,Homme_seul_en_pct,Femme_seul_en_pct,Fpcae_en_pct,Fpcse_en_pct,Fpm_en_pct,Mcuf_en_pct,Maup_en_pct,Msfapp_en_pct
0,10002,Ailleville,81.617355,79.508247,23.425759,27.463314,10.985325,184.551361,0.000000,38.448639,...,28.76,45.75,4.926155,12.315387,36.599711,35.653922,10.504825,82.758458,17.241542,0.000000
1,10003,Aix-Villemaur-Pâlis,1318.732819,1064.587185,265.840077,303.373495,288.694133,2649.160081,20.150397,592.067628,...,25.05,52.73,8.851906,9.302003,40.434834,32.642250,8.151158,81.228241,18.153909,0.617849
2,10004,Allibaudières,93.873704,52.152058,15.645617,10.430412,10.430412,161.671379,10.430412,20.860823,...,20.00,68.70,5.405406,5.405406,48.648649,27.027027,8.108108,83.783784,10.810811,5.405406
3,10005,Amance,97.622791,94.899149,0.000000,41.182449,10.295612,192.521939,0.000000,51.478061,...,26.03,57.53,4.219513,16.878053,40.009341,38.893094,0.000000,78.902434,21.097566,0.000000
4,10006,Arcis-sur-Aube,903.761393,716.171522,480.392539,324.403512,219.555106,2100.325453,39.697953,543.958618,...,26.45,53.68,8.180200,12.086650,33.672409,26.683171,17.898501,78.254080,20.266850,1.479069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31573,95676,Villers-en-Arthies,277.866607,111.793995,45.405640,31.160255,20.773503,435.066242,0.000000,51.933758,...,27.51,45.86,4.265606,6.398410,57.056798,22.955646,9.323540,89.335984,10.664016,0.000000
31574,95678,Villiers-Adam,503.811765,219.482353,39.905882,24.941176,59.858824,763.200000,0.000000,84.800000,...,31.33,42.94,7.058824,2.941176,59.411765,25.882353,4.705882,90.000000,10.000000,0.000000
31575,95680,Villiers-le-Bel,16868.584767,3046.680721,5391.485967,1432.820914,1414.116321,25306.751455,556.640496,2846.937235,...,19.34,21.56,4.925462,4.990611,58.754411,10.611793,18.778907,88.145111,9.916073,1.938816
31576,95682,Villiers-le-Sec,136.714286,47.142857,0.000000,4.714286,9.428571,183.857143,0.000000,14.142857,...,29.47,38.95,4.761905,2.380953,69.047619,23.809524,0.000000,92.857143,7.142857,0.000000
31577,95690,Wy-dit-Joli-Village,135.777778,104.444444,15.666667,26.111111,26.111111,255.888889,20.888889,52.222222,...,31.60,39.83,7.936508,7.936508,41.269841,31.746032,4.761905,77.777778,15.873016,6.349206

In [90]:
data = filtered.copy()

x = ["Homme_seul_en_pct", 'Femme_seul_en_pct' ,'Fpcae_en_pct', "Fpcse_en_pct", 'Fpm_en_pct','Mcuf_en_pct', 'Msfapp_en_pct', 'Maup_en_pct']
y = ["pct_gauche", "pct_centre", "pct_droite"]

corr = data[x + y].corr()

res = corr.loc[x, y]

res

                   pct_gauche  pct_centre  pct_droite
Homme_seul_en_pct    0.126757   -0.019676   -0.090335
Femme_seul_en_pct    0.162923    0.038697   -0.161400
Fpcae_en_pct        -0.130638   -0.046725    0.140529
Fpcse_en_pct        -0.066586    0.130743   -0.037767
Fpm_en_pct           0.132936   -0.096793   -0.040843
Mcuf_en_pct         -0.198853   -0.014096    0.173542
Msfapp_en_pct        0.068435    0.004895   -0.059761
Maup_en_pct          0.196879    0.013939   -0.171806

In [ ]:
def commune(habitants):
    if habitants < 2000:
        return "rurale"
    elif habitants < 10000:
        return "petite_commune"
    elif habitants < 50000:
        return "ville_moyenne"
    elif habitants < 100000:
        return "grande_ville"
    else:
        return "tres_grande_ville"

filtered["categorie_commune"] = filtered["Total"].apply(commune)
filtered[["CITY", "Total", "categorie_commune"]].head()

                  CITY        Total categorie_commune
0           Ailleville   223.000000            rurale
1  Aix-Villemaur-Pâlis  3261.378105    petite_commune
2        Allibaudières   192.962614            rurale
3               Amance   244.000000            rurale
4       Arcis-sur-Aube  2683.982024    petite_commune

In [87]:
filtered.groupby("categorie_commune")[["pct_gauche", "pct_centre", "pct_droite", "pct_blancs"]].mean()

                   pct_gauche  pct_centre  pct_droite  pct_blancs
categorie_commune
grande_ville        43.184189   28.785270   28.030270    1.373919
petite_commune      27.878659   31.520602   40.600808    1.584040
rurale              24.959537   30.569728   44.470680    1.659811
tres_grande_ville   43.592308   30.020000   26.387179    1.383077
ville_moyenne       34.691575   30.196889   35.112010    1.432625