## Imports

In [21]:
import pandas as pd

df_election = pd.read_csv('src/election.csv', sep=';')
df_insee = pd.read_csv('src/insee.csv', sep=';', dtype={'Code_INSEE': str})

df_insee_2022 = df_insee[df_insee['Année'] == 2022].copy()
df_insee_2011 = df_insee[df_insee['Année'] == 2011].copy()
df_insee_2016 = df_insee[df_insee['Année'] == 2016].copy()

In [22]:
df_election.columns

Index(['Année', 'Code_INSEE', 'Libellé de la commune', 'Inscrits',
       'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins', 'Blancs',
       '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins', '% Nuls/Vot',
       'Exprimés', '% Exp/Ins', '% Exp/Vot', '% gauche/Exp', '% centre/Exp',
       '% droite/Exp', 'Résultat'],
      dtype='object')

## Aperçu des deux dataframes

In [23]:
display(df_election)
display(df_insee_2022)

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,% gauche/Exp,% centre/Exp,% droite/Exp,Résultat
0,2022,01001,L'Abergement-Clémenciat,645,108,16.74,537,83.26,16,2.48,...,1,0.16,0.19,520,80.62,96.83,21.73,32.31,45.96,droite
1,2022,01002,L'Abergement-de-Varey,213,38,17.84,175,82.16,3,1.41,...,1,0.47,0.57,171,80.28,97.71,38.60,35.09,26.32,gauche
2,2022,01004,Ambérieu-en-Bugey,8765,2078,23.71,6687,76.29,88,1.00,...,46,0.52,0.69,6553,74.76,98.00,34.44,24.87,40.68,droite
3,2022,01005,Ambérieux-en-Dombes,1282,234,18.25,1048,81.75,14,1.09,...,6,0.47,0.57,1028,80.19,98.09,21.50,29.47,49.03,droite
4,2022,01006,Ambléon,103,23,22.33,80,77.67,3,2.91,...,0,0.00,0.00,77,74.76,96.25,32.47,29.87,37.66,droite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35240,2022,ZZ229,Zurich,24868,14101,56.70,10767,43.30,40,0.16,...,31,0.12,0.29,10696,43.01,99.34,26.67,54.92,18.41,centre
35241,2022,ZZ231,Taipei,1709,942,55.12,767,44.88,8,0.47,...,2,0.12,0.26,757,44.29,98.70,37.38,39.23,23.38,centre
35242,2022,ZZ233,Nour-Soultan,117,64,54.70,53,45.30,2,1.71,...,0,0.00,0.00,51,43.59,96.23,27.45,50.98,21.57,centre
35243,2022,ZZ234,Monterrey,713,553,77.56,160,22.44,0,0.00,...,2,0.28,1.25,158,22.16,98.75,20.89,61.39,17.72,centre
35244,2022,ZZ235,Bahamas (Nassau),136,78,57.35,58,42.65,3,2.21,...,0,0.00,0.00,55,40.44,94.83,5.45,45.45,49.09,droite

,Code_INSEE,Année,Femmes,Hommes,Agriculteurs,Artisans,Cadres,Intermédiaires,Employés,Ouvriers,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
69694,01001,2022,328.874286,363.234286,4.908571,39.268571,73.628571,103.080000,107.988571,122.714286,...,131.000000,128.000000,44.000000,357.000000,55.000000,115.000000,41.000000,22.000000,107.000000,697.000000
69695,01002,2022,89.345455,109.200000,24.818182,4.963636,19.854545,29.781818,19.854545,19.854545,...,26.000000,32.000000,18.000000,103.000000,24.000000,21.000000,7.000000,16.000000,45.000000,216.000000
69696,01004,2022,6660.206201,5934.302494,16.032418,392.232934,983.205730,1944.301069,2236.854970,2000.879335,...,1818.260858,2040.179086,769.098809,5158.413539,734.930321,1253.876355,853.759327,1078.958883,3481.713288,12594.508695
69697,01005,2022,798.103479,744.261328,5.636287,101.904045,135.089600,237.649785,328.753738,216.496239,...,268.831175,239.134291,86.467498,758.673406,121.875706,220.625154,71.867895,70.087419,311.225980,1554.355560
69698,01006,2022,41.454545,57.000000,0.000000,0.000000,0.000000,10.363636,15.545455,46.636364,...,24.000000,26.000000,6.000000,51.000000,9.000000,11.000000,3.000000,10.000000,20.000000,104.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104537,97420,2022,10087.120406,9015.567783,126.142445,542.557926,947.418529,2586.674550,4041.906300,2612.259982,...,3218.505670,2227.387976,512.451059,6814.282260,433.224376,2668.173405,849.563055,743.843089,7699.188719,19208.274904
104538,97421,2022,2740.307107,2836.925200,207.887935,148.779093,61.700211,355.830405,943.213397,1175.327670,...,920.135698,711.673239,216.556600,2135.625612,42.077795,885.747391,364.591721,182.186255,2021.318596,5631.547370
104539,97422,2022,33811.692991,30513.284058,1180.842480,2872.608457,2590.061227,7725.489486,13002.171632,8290.660632,...,10702.949499,8832.705369,2531.656529,23842.224861,1470.169696,8225.022218,3182.951611,4443.439985,23050.868985,64324.977049
104540,97423,2022,2948.329422,2744.765843,55.003507,153.178643,208.397826,609.751973,1350.268634,1051.467021,...,981.866515,790.522607,236.122699,1987.170562,109.654431,796.401298,341.745004,226.625105,2293.304136,5754.900536
104541,97424,2022,2080.112353,2127.868896,67.346530,139.840622,30.683191,315.697098,926.833294,803.397138,...,827.796101,592.651834,196.853138,1465.862327,59.032029,597.994947,272.781624,200.983398,1579.297889,4207.981248

## Suppresion Des Valeurs NaN

In [24]:
null = df_insee.isna().any(axis=1)
display(df_insee[null])
df_insee = df_insee[~null]

,Code_INSEE,Année,Femmes,Hommes,Agriculteurs,Artisans,Cadres,Intermédiaires,Employés,Ouvriers,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
8954,26030,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.400000,1.400000,0.0,1.400000,0.0,0.0,0.0,1.4,2.8,5.6
9184,26274,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0
11348,31127,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.250000,0.000000,0.0,2.500000,0.0,0.0,0.0,0.0,2.5,5.0
19682,54310,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,1.0,3.0
43798,26030,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.333333,1.666667,0.0,3.333333,0.0,0.0,0.0,0.0,0.0,5.0
44028,26274,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
46192,31127,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,3.0
54526,54310,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,3.0
55136,55394,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.200000,2.400000,0.0,4.800000,0.0,0.0,0.0,0.0,0.0,6.0
55994,57470,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,5.600000,0.0,5.600000,0.0,0.0,0.0,0.0,0.0,7.0
60317,65134,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,4.000000,0.0,6.000000,0.0,0.0,0.0,0.0,0.0,13.0
78633,26018,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,1.000000,0.0,2.000000,0.0,4.0,0.0,0.0,2.0,8.0
81038,31127,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,3.000000,0.0,3.000000,0.0,0.0,0.0,0.0,0.0,3.0
89372,54310,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,2.0
100861,80270,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,2.000000,0.0,6.000000,0.0,0.0,0.0,1.0,0.0,7.0

In [25]:
null = df_election.isna().any(axis=1)
display(df_election[null])
df_election = df_election[~null]

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,% gauche/Exp,% centre/Exp,% droite/Exp,Résultat
468,2022,02078,Besmé,113,20,17.70,93,82.30,0,0.0,...,93,82.30,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
482,2022,02093,Blérancourt,867,227,26.18,640,73.82,0,0.0,...,640,73.82,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
6605,2022,2A065,Cargèse,997,399,40.02,598,59.98,0,0.0,...,598,59.98,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
8348,2022,24130,Condat-sur-Vézère,689,139,20.17,550,79.83,0,0.0,...,550,79.83,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
14210,2022,38211,Lieudieu,259,62,23.94,197,76.06,0,0.0,...,197,76.06,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
15768,2022,42152,Nandax,432,89,20.60,343,79.40,0,0.0,...,343,79.40,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
22745,2022,60316,Hodenc-l'Evêque,209,42,20.10,167,79.90,0,0.0,...,167,79.90,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
22818,2022,60391,Maysel,203,45,22.17,158,77.83,0,0.0,...,158,77.83,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
22925,2022,60504,Ponchon,747,141,18.88,606,81.12,0,0.0,...,606,81.12,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
23981,2022,62494,Léchelle,41,11,26.83,30,73.17,0,0.0,...,30,73.17,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
24351,2022,62868,Wail,220,41,18.64,179,81.36,0,0.0,...,179,81.36,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
30952,2022,79310,Secondigné-sur-Belle,390,69,17.69,321,82.31,0,0.0,...,321,82.31,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
33410,2022,88128,Denipaire,208,44,21.15,164,78.85,0,0.0,...,164,78.85,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
34987,2022,ZP716,Fakarava,1382,712,51.52,670,48.48,0,0.0,...,670,48.48,100.0,0,0.0,0.0,NaN,NaN,NaN,NaN
35202,2022,ZZ186,Sanaa,73,73,100.00,0,0.00,0,0.0,...,0,0.00,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN
35208,2022,ZZ193,Shanghai,4619,4619,100.00,0,0.00,0,0.0,...,0,0.00,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN

## Fusion des deux dataframes

In [26]:
print('Nombre de communes Data Gouv :', len(df_election))
print('Nombre de communes INSEE :', len(df_insee_2022))

df_stats = pd.merge(df_election, df_insee_2022, on=['Année', 'Code_INSEE'], how='inner')
df_model = pd.merge(df_election[['Année', 'Code_INSEE', 'Résultat']], df_insee_2022, on=['Année', 'Code_INSEE'], how='inner')
display(df_model)

Nombre de communes Data Gouv : 35229
Nombre de communes INSEE : 34848

,Année,Code_INSEE,Résultat,Femmes,Hommes,Agriculteurs,Artisans,Cadres,Intermédiaires,Employés,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
0,2022,01001,droite,328.874286,363.234286,4.908571,39.268571,73.628571,103.080000,107.988571,...,131.000000,128.000000,44.000000,357.000000,55.000000,115.000000,41.000000,22.000000,107.000000,697.000000
1,2022,01002,gauche,89.345455,109.200000,24.818182,4.963636,19.854545,29.781818,19.854545,...,26.000000,32.000000,18.000000,103.000000,24.000000,21.000000,7.000000,16.000000,45.000000,216.000000
2,2022,01004,droite,6660.206201,5934.302494,16.032418,392.232934,983.205730,1944.301069,2236.854970,...,1818.260858,2040.179086,769.098809,5158.413539,734.930321,1253.876355,853.759327,1078.958883,3481.713288,12594.508695
3,2022,01005,droite,798.103479,744.261328,5.636287,101.904045,135.089600,237.649785,328.753738,...,268.831175,239.134291,86.467498,758.673406,121.875706,220.625154,71.867895,70.087419,311.225980,1554.355560
4,2022,01006,droite,41.454545,57.000000,0.000000,0.000000,0.000000,10.363636,15.545455,...,24.000000,26.000000,6.000000,51.000000,9.000000,11.000000,3.000000,10.000000,20.000000,104.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34710,2022,95676,droite,210.196629,169.755939,0.000000,20.221523,35.135483,94.824571,79.137430,...,63.580874,65.305688,17.417783,182.283388,17.842724,60.270014,19.626753,23.755654,80.845508,384.624042
34711,2022,95678,droite,319.247059,359.152941,0.000000,54.870588,114.729412,144.658824,74.823529,...,122.000000,96.000000,50.000000,320.000000,71.000000,90.000000,35.000000,32.000000,152.000000,700.000000
34712,2022,95680,gauche,11144.103286,10452.072763,0.000000,639.813936,882.423154,2590.873430,4525.300632,...,2943.191733,2313.955556,707.841948,9711.794617,254.462856,1615.639951,895.822727,1141.682877,7954.497162,21596.176049
34713,2022,95682,droite,75.428571,75.428571,0.000000,4.714286,23.571429,33.000000,37.714286,...,13.619048,11.523810,9.428571,68.095238,10.476190,24.095238,6.285714,5.238095,33.523810,150.857143
34714,2022,95690,droite,146.222222,146.222222,10.444444,5.222222,73.111111,47.000000,20.888889,...,77.000000,54.000000,19.000000,131.000000,30.000000,33.000000,22.000000,19.000000,42.000000,292.444444

In [27]:
df_stats = pd.concat([df_stats, df_insee_2011, df_insee_2016], ignore_index=True)

df_stats = df_stats.sort_values(['Code_INSEE', 'Année']).reset_index(drop=True)

display(df_stats)

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
0,2011,01001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.000000,97.000000,30.000000,357.000000,0.0,0.0,42.000000,30.000000,172.000000,620.000000
1,2016,01001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.000000,111.000000,32.000000,320.000000,0.0,0.0,0.000000,0.000000,0.000000,606.000000
2,2022,01001,L'Abergement-Clémenciat,645.0,108.0,16.74,537.0,83.26,16.0,2.48,...,131.000000,128.000000,44.000000,357.000000,55.0,115.0,41.000000,22.000000,107.000000,697.000000
3,2011,01002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.000000,28.000000,13.000000,102.000000,0.0,0.0,9.000000,10.000000,69.000000,190.000000
4,2016,01002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.000000,33.000000,11.000000,89.000000,0.0,0.0,0.000000,0.000000,0.000000,195.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104404,2016,97422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8699.023257,6962.839359,1942.532904,22862.619725,0.0,0.0,0.000000,0.000000,0.000000,59247.833492
104405,2011,97423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,609.479765,487.697055,174.549857,1902.982014,0.0,0.0,300.541387,130.685381,3068.153211,5402.361993
104406,2016,97423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,738.838894,549.231651,188.348818,1822.561973,0.0,0.0,0.000000,0.000000,0.000000,5586.391067
104407,2011,97424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,513.731258,508.529212,129.174339,1653.863204,0.0,0.0,294.594383,126.107069,2227.412108,4324.582489
104408,2016,97424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,615.914266,530.118388,162.395401,1492.265089,0.0,0.0,0.000000,0.000000,0.000000,4204.838806

## Identification des valeurs manquantes

Récupérer un dictionnaire code-libellé depuis les métadonnées du csv population
Et comparer les libellés des communes manquantes avec les libellés présents dans le dict

In [28]:
# # Communes présentes dans df_insee mais absentes de df_elections
# df_null_election = df_stats[df_stats['Libellé de la commune'].isnull()]
# display(df_null_election)

# # Communes présentes dans df_election mais absentes de df_insee
# df_null_insee = df_stats[df_stats['Population_active'].isnull()]
# display(df_null_insee)

## Création des CSV

In [29]:
df_stats.to_csv('df_stats.csv', index=False, sep=';', encoding='utf-8')
df_model.to_csv('df_complet.csv', index=False, sep=';', encoding='utf-8')