## Imports

In [42]:
import pandas as pd

df_election = pd.read_csv('src/election.csv', sep=';')
df_insee = pd.read_csv('src/insee.csv', sep=';', dtype={'Code_INSEE': str})

df_insee_2022 = df_insee[df_insee['Année'] == 2022].copy()
df_insee_2011 = df_insee[df_insee['Année'] == 2011].copy()
df_insee_2016 = df_insee[df_insee['Année'] == 2016].copy()
df_insee_2011['Année'] = 2012
df_insee_2016['Année'] = 2017

/tmp/ipykernel_41431/3702413846.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_election = pd.read_csv('src/election.csv', sep=';')

In [43]:
df_election.columns

Index(['Année', 'Code_INSEE', 'Libellé de la commune', 'Inscrits',
       'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins', 'Blancs',
       '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins', '% Nuls/Vot',
       'Exprimés', '% Exp/Ins', '% Exp/Vot', '% gauche/Exp', '% centre/Exp',
       '% droite/Exp', 'Résultat'],
      dtype='object')

## Aperçu des deux dataframes

In [44]:
display(df_election)
display(df_insee_2022)

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,% gauche/Exp,% centre/Exp,% droite/Exp,Résultat
0,2022,01001,L'Abergement-Clémenciat,645.0,108.0,16.740000,537.0,83.260000,16.0,2.48000,...,1.0,0.16,0.19,520.0,80.620000,96.830000,21.730000,32.310000,45.960000,droite
1,2017,01001,L'Abergement-Clémenciat,598.0,92.0,15.380000,506.0,84.620000,2.0,0.33000,...,9.0,1.51,1.78,495.0,82.780000,97.830000,19.400000,24.440000,56.150000,droite
2,2012,01001,L'Abergement-Clémenciat,592.0,84.0,14.189189,508.0,85.810811,9.0,1.52027,...,0.0,0.00,0.00,499.0,84.290541,98.228346,30.861723,10.821643,58.316633,droite
3,2017,01002,L'Abergement-de-Varey,209.0,25.0,11.960000,184.0,88.040000,6.0,2.87000,...,2.0,0.96,1.09,176.0,84.210000,95.650000,23.870000,21.020000,55.120000,droite
4,2022,01002,L'Abergement-de-Varey,213.0,38.0,17.840000,175.0,82.160000,3.0,1.41000,...,1.0,0.47,0.57,171.0,80.280000,97.710000,38.600000,35.090000,26.320000,gauche
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105141,2022,ZZ229,Zurich,24868.0,14101.0,56.700000,10767.0,43.300000,40.0,0.16000,...,31.0,0.12,0.29,10696.0,43.010000,99.340000,26.670000,54.920000,18.410000,centre
105142,2022,ZZ231,Taipei,1709.0,942.0,55.120000,767.0,44.880000,8.0,0.47000,...,2.0,0.12,0.26,757.0,44.290000,98.700000,37.380000,39.230000,23.380000,centre
105143,2022,ZZ233,Nour-Soultan,117.0,64.0,54.700000,53.0,45.300000,2.0,1.71000,...,0.0,0.00,0.00,51.0,43.590000,96.230000,27.450000,50.980000,21.570000,centre
105144,2022,ZZ234,Monterrey,713.0,553.0,77.560000,160.0,22.440000,0.0,0.00000,...,2.0,0.28,1.25,158.0,22.160000,98.750000,20.890000,61.390000,17.720000,centre
105145,2022,ZZ235,Bahamas (Nassau),136.0,78.0,57.350000,58.0,42.650000,3.0,2.21000,...,0.0,0.00,0.00,55.0,40.440000,94.830000,5.450000,45.450000,49.090000,droite

,Code_INSEE,Année,Femmes,Hommes,Agriculteurs,Artisans,Cadres,Intermédiaires,Employés,Ouvriers,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
69694,01001,2022,328.874286,363.234286,4.908571,39.268571,73.628571,103.080000,107.988571,122.714286,...,131.000000,128.000000,44.000000,357.000000,55.000000,115.000000,41.000000,22.000000,107.000000,697.000000
69695,01002,2022,89.345455,109.200000,24.818182,4.963636,19.854545,29.781818,19.854545,19.854545,...,26.000000,32.000000,18.000000,103.000000,24.000000,21.000000,7.000000,16.000000,45.000000,216.000000
69696,01004,2022,6660.206201,5934.302494,16.032418,392.232934,983.205730,1944.301069,2236.854970,2000.879335,...,1818.260858,2040.179086,769.098809,5158.413539,734.930321,1253.876355,853.759327,1078.958883,3481.713288,12594.508695
69697,01005,2022,798.103479,744.261328,5.636287,101.904045,135.089600,237.649785,328.753738,216.496239,...,268.831175,239.134291,86.467498,758.673406,121.875706,220.625154,71.867895,70.087419,311.225980,1554.355560
69698,01006,2022,41.454545,57.000000,0.000000,0.000000,0.000000,10.363636,15.545455,46.636364,...,24.000000,26.000000,6.000000,51.000000,9.000000,11.000000,3.000000,10.000000,20.000000,104.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104537,97420,2022,10087.120406,9015.567783,126.142445,542.557926,947.418529,2586.674550,4041.906300,2612.259982,...,3218.505670,2227.387976,512.451059,6814.282260,433.224376,2668.173405,849.563055,743.843089,7699.188719,19208.274904
104538,97421,2022,2740.307107,2836.925200,207.887935,148.779093,61.700211,355.830405,943.213397,1175.327670,...,920.135698,711.673239,216.556600,2135.625612,42.077795,885.747391,364.591721,182.186255,2021.318596,5631.547370
104539,97422,2022,33811.692991,30513.284058,1180.842480,2872.608457,2590.061227,7725.489486,13002.171632,8290.660632,...,10702.949499,8832.705369,2531.656529,23842.224861,1470.169696,8225.022218,3182.951611,4443.439985,23050.868985,64324.977049
104540,97423,2022,2948.329422,2744.765843,55.003507,153.178643,208.397826,609.751973,1350.268634,1051.467021,...,981.866515,790.522607,236.122699,1987.170562,109.654431,796.401298,341.745004,226.625105,2293.304136,5754.900536
104541,97424,2022,2080.112353,2127.868896,67.346530,139.840622,30.683191,315.697098,926.833294,803.397138,...,827.796101,592.651834,196.853138,1465.862327,59.032029,597.994947,272.781624,200.983398,1579.297889,4207.981248

## Suppresion Des Valeurs NaN

In [45]:
null = df_insee.isna().any(axis=1)
display(df_insee[null])
df_insee = df_insee[~null]

,Code_INSEE,Année,Femmes,Hommes,Agriculteurs,Artisans,Cadres,Intermédiaires,Employés,Ouvriers,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
8954,26030,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.400000,1.400000,0.0,1.400000,0.0,0.0,0.0,1.4,2.8,5.6
9184,26274,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0
11348,31127,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.250000,0.000000,0.0,2.500000,0.0,0.0,0.0,0.0,2.5,5.0
19682,54310,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,1.0,3.0
43798,26030,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.333333,1.666667,0.0,3.333333,0.0,0.0,0.0,0.0,0.0,5.0
44028,26274,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
46192,31127,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,3.0
54526,54310,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,3.0
55136,55394,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.200000,2.400000,0.0,4.800000,0.0,0.0,0.0,0.0,0.0,6.0
55994,57470,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,5.600000,0.0,5.600000,0.0,0.0,0.0,0.0,0.0,7.0
60317,65134,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,4.000000,0.0,6.000000,0.0,0.0,0.0,0.0,0.0,13.0
78633,26018,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,1.000000,0.0,2.000000,0.0,4.0,0.0,0.0,2.0,8.0
81038,31127,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,3.000000,0.0,3.000000,0.0,0.0,0.0,0.0,0.0,3.0
89372,54310,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,0.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,2.0
100861,80270,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,2.000000,0.0,6.000000,0.0,0.0,0.0,1.0,0.0,7.0

In [46]:
null = df_election.isna().any(axis=1)
display(df_election[null])
df_election = df_election[~null]

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,% gauche/Exp,% centre/Exp,% droite/Exp,Résultat
1397,2022,02078,Besmé,113.0,20.0,17.70,93.0,82.30,0.0,0.0,...,93.0,82.30,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1439,2022,02093,Blérancourt,867.0,227.0,26.18,640.0,73.82,0.0,0.0,...,640.0,73.82,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
23893,2022,24130,Condat-sur-Vézère,689.0,139.0,20.17,550.0,79.83,0.0,0.0,...,550.0,79.83,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
31617,2022,2A065,Cargèse,997.0,399.0,40.02,598.0,59.98,0.0,0.0,...,598.0,59.98,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
42510,2022,38211,Lieudieu,259.0,62.0,23.94,197.0,76.06,0.0,0.0,...,197.0,76.06,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
47162,2022,42152,Nandax,432.0,89.0,20.60,343.0,79.40,0.0,0.0,...,343.0,79.40,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
68044,2022,60316,Hodenc-l'Evêque,209.0,42.0,20.10,167.0,79.90,0.0,0.0,...,167.0,79.90,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
68264,2022,60391,Maysel,203.0,45.0,22.17,158.0,77.83,0.0,0.0,...,158.0,77.83,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
68586,2022,60504,Ponchon,747.0,141.0,18.88,606.0,81.12,0.0,0.0,...,606.0,81.12,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
71750,2022,62494,Léchelle,41.0,11.0,26.83,30.0,73.17,0.0,0.0,...,30.0,73.17,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
72860,2022,62868,Wail,220.0,41.0,18.64,179.0,81.36,0.0,0.0,...,179.0,81.36,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
92580,2022,79310,Secondigné-sur-Belle,390.0,69.0,17.69,321.0,82.31,0.0,0.0,...,321.0,82.31,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
99933,2022,88128,Denipaire,208.0,44.0,21.15,164.0,78.85,0.0,0.0,...,164.0,78.85,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
104634,2022,ZP716,Fakarava,1382.0,712.0,51.52,670.0,48.48,0.0,0.0,...,670.0,48.48,100.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
105067,2022,ZZ186,Sanaa,73.0,73.0,100.00,0.0,0.00,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
105078,2022,ZZ193,Shanghai,4619.0,4619.0,100.00,0.0,0.00,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

## Fusion des deux dataframes

In [47]:
print('Nombre de communes Data Gouv :', len(df_election))
print('Nombre de communes INSEE :', len(df_insee_2022))

df_insee_all = pd.concat([
    df_insee_2011,
    df_insee_2016,
    df_insee_2022
], ignore_index=True)

df_stats = pd.merge(df_election, df_insee_all, on=['Année', 'Code_INSEE'], how='inner')
df_model = pd.merge(df_election[['Année', 'Code_INSEE', 'Résultat']], df_insee_2022, on=['Année', 'Code_INSEE'], how='inner')
display(df_stats)

Nombre de communes Data Gouv : 105130
Nombre de communes INSEE : 34848

,Année,Code_INSEE,Libellé de la commune,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,...,55-64 ans,65-79 ans,80 ans et +,Mariés,Pacsés,Concubinage,Veufs,Divorcés,Célibataires,Population_active
0,2022,01001,L'Abergement-Clémenciat,645.0,108.0,16.740000,537.0,83.260000,16.0,2.480000,...,131.000000,128.000000,44.000000,357.000000,55.00000,115.000000,41.000000,22.000000,107.00000,697.000000
1,2017,01001,L'Abergement-Clémenciat,598.0,92.0,15.380000,506.0,84.620000,2.0,0.330000,...,95.000000,111.000000,32.000000,320.000000,0.00000,0.000000,0.000000,0.000000,0.00000,606.000000
2,2012,01001,L'Abergement-Clémenciat,592.0,84.0,14.189189,508.0,85.810811,9.0,1.520270,...,98.000000,97.000000,30.000000,357.000000,0.00000,0.000000,42.000000,30.000000,172.00000,620.000000
3,2017,01002,L'Abergement-de-Varey,209.0,25.0,11.960000,184.0,88.040000,6.0,2.870000,...,25.000000,33.000000,11.000000,89.000000,0.00000,0.000000,0.000000,0.000000,0.00000,195.000000
4,2022,01002,L'Abergement-de-Varey,213.0,38.0,17.840000,175.0,82.160000,3.0,1.410000,...,26.000000,32.000000,18.000000,103.000000,24.00000,21.000000,7.000000,16.000000,45.00000,216.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38482,2012,95682,Villiers-le-Sec,95.0,11.0,11.578947,84.0,88.421053,0.0,0.000000,...,13.443182,12.409091,4.136364,58.943182,0.00000,0.000000,8.272727,14.477273,56.87500,138.568182
38483,2022,95682,Villiers-le-Sec,110.0,14.0,12.730000,96.0,87.270000,0.0,0.000000,...,13.619048,11.523810,9.428571,68.095238,10.47619,24.095238,6.285714,5.238095,33.52381,150.857143
38484,2017,95690,Wy-dit-Joli-Village,309.0,46.0,14.890000,263.0,85.110000,2.0,0.650000,...,63.000000,53.000000,15.000000,129.000000,0.00000,0.000000,0.000000,0.000000,0.00000,295.000000
38485,2022,95690,Wy-dit-Joli-Village,285.0,48.0,16.840000,237.0,83.160000,4.0,1.400000,...,77.000000,54.000000,19.000000,131.000000,30.00000,33.000000,22.000000,19.000000,42.00000,292.444444
38486,2012,95690,Wy-dit-Joli-Village,279.0,30.0,10.752688,249.0,89.247312,1.0,0.358423,...,55.000000,39.000000,9.000000,135.000000,0.00000,0.000000,15.000000,25.000000,108.00000,296.000000

In [48]:
# df_stats = pd.concat([df_stats, df_insee_2011, df_insee_2016], ignore_index=True)

# df_stats = df_stats.sort_values(['Code_INSEE', 'Année']).reset_index(drop=True)

# display(df_stats)

## Identification des valeurs manquantes

Récupérer un dictionnaire code-libellé depuis les métadonnées du csv population
Et comparer les libellés des communes manquantes avec les libellés présents dans le dict

In [49]:
# Communes présentes dans df_insee mais absentes de df_elections
df_null_election = df_stats[df_stats['Libellé de la commune'].isnull()]
display(df_null_election)

# Communes présentes dans df_election mais absentes de df_insee
df_null_insee = df_stats[df_stats['Population_active'].isnull()]
display(df_null_insee)

Empty DataFrame
Columns: [Année, Code_INSEE, Libellé de la commune, Inscrits, Abstentions, % Abs/Ins, Votants, % Vot/Ins, Blancs, % Blancs/Ins, % Blancs/Vot, Nuls, % Nuls/Ins, % Nuls/Vot, Exprimés, % Exp/Ins, % Exp/Vot, % gauche/Exp, % centre/Exp, % droite/Exp, Résultat, Femmes, Hommes, Agriculteurs, Artisans, Cadres, Intermédiaires, Employés, Ouvriers, Retraités, Etudiants, Inactifs, Personne seule, Homme seul, Femme seule, Colocation, Famille, Famille monoparentale, Couple sans enfant, Couple avec enfants, Population avec enfants, 15-24 ans, 25-39 ans, 40-54 ans, 55-64 ans, 65-79 ans, 80 ans et +, Mariés, Pacsés, Concubinage, Veufs, Divorcés, Célibataires, Population_active]
Index: []

[0 rows x 54 columns]

Empty DataFrame
Columns: [Année, Code_INSEE, Libellé de la commune, Inscrits, Abstentions, % Abs/Ins, Votants, % Vot/Ins, Blancs, % Blancs/Ins, % Blancs/Vot, Nuls, % Nuls/Ins, % Nuls/Vot, Exprimés, % Exp/Ins, % Exp/Vot, % gauche/Exp, % centre/Exp, % droite/Exp, Résultat, Femmes, Hommes, Agriculteurs, Artisans, Cadres, Intermédiaires, Employés, Ouvriers, Retraités, Etudiants, Inactifs, Personne seule, Homme seul, Femme seule, Colocation, Famille, Famille monoparentale, Couple sans enfant, Couple avec enfants, Population avec enfants, 15-24 ans, 25-39 ans, 40-54 ans, 55-64 ans, 65-79 ans, 80 ans et +, Mariés, Pacsés, Concubinage, Veufs, Divorcés, Célibataires, Population_active]
Index: []

[0 rows x 54 columns]

## Création des CSV

In [50]:
df_stats.to_csv('df_stats.csv', index=False, sep=';', encoding='utf-8')
df_model.to_csv('df_complet.csv', index=False, sep=';', encoding='utf-8')